apiVersion: v1
kind: Service
metadata:
  name: es-svc-endpoint
spec:
  selector:
    app: es-cluster
  ports:
  - name: http
    port: 9200
    targetPort: 9200
#    nodePort: 31920
#  type: NodePort
