apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dev
  labels:
    name: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongod
