apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: tungpv
  POSTGRES_USER: tungpv
  POSTGRES_PASSWORD: tungpv
  PGDATA: /var/lib/postgresql/data/pgdata
