---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mongodb-0-service
  labels:
    run: mongodb-0-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    defacementComponent: mongodb-0

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mongodb-1-service
  labels:
    run: mongodb-1-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    defacementComponent: mongodb-1

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mongodb-2-service
  labels:
    run: mongodb-2-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    defacementComponent: mongodb-2