apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.10
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
          envFrom:
            - configMapRef:
                name: redis-cluster
          volumeMounts:
            - mountPath: /data
              name: redis-storage-claim
  volumeClaimTemplates:
  - metadata:
      name: redis-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: nfs-storageclass
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi